### PR TITLE
Correctly classify keywords in object-heritage clauses

### PR DESCRIPTION
**Pull request by anubmat**
Solving Issue #38 / #89. 
Improving upon the previous pull request #99

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
In what way is this an improvement?

**Comment by anubmat** [comment]
The earlier fix was insufficient. We looked for word boundaries but not spaces. 
Example:
Regexp  "{\bname" matches 
take1
but does not match
take2
However, Regexp "{\s*\bname" matches both.

Spaces before the word 'implement' after 'extends' or vice-versa were not being matched/consumed by any of the patterns (Cant say why they are not being ignored)

**Comment by zhengbli** [comment]
This is a little weird as I think `(?:\b(extends|implements)\b)` should cover the same cases with `(?:\s*\b(extends|implements)\b)`. I'm guessing the reason why they behave differently was that some other pattern may match the spaces and then takes the chance for this pattern to function. 

Can you add to the test what cases that wasn't working after #99 but was fixed by this PR? That way we'll make sure the test is comprehensive.

**Comment by anubmat** [comment]
Thanks @zhengbli. Your guess was right. There were spaces in the beginning of object-heritage parent which made it difficult for regexp to match. Output looks right too!

**Comment by zhengbli** [comment]
:+1:

**Pull request merged**
