### PR TITLE
Rewrite and fixes for lot of grammar issues

### PR DESCRIPTION
**Pull request by sheetalkamat**

### CODE REVIEW

**Comment by sheetalkamat** [comment]
merging this as suggested by @mhegazy

**Comment by Tyriar** [comment]
Nice work! Looking forward to testing it out.

**Comment by whitecolor** [comment]
When it will be available?

**Comment by whitecolor** [comment]
Should it also effect on this?
https://github.com/Microsoft/vscode/issues/11398

And when will it be available?

**Comment by mhegazy** [comment]
> And when will it be available?

we should have this in a vscode extension for users to try it out next week. if every thing looks good, should be available in vscode's subsequent releases.

**Comment by octref** [comment]
@mhegazy 

Thanks a lot for the hard work! Can you give an overview of the most important grammar issues that get fixed in this PR?

**Comment by mhegazy** [comment]
there are some 120 issues that are fixed by this change (linked above). it is almost a rewrite at this point. give it a try and let us know if there are other issues we are not aware of.

**Comment by whitecolor** [comment]
> give it a try and let us know if there are other issues we are not aware of.

So it is not available yet right? What will be need to it out, just use vscode insiders?

**Comment by sheetalkamat** [comment]
@whitecolor the issue you mentioned seems to be fixed.

**Comment by farfromrefug** [comment]
@sheetalkamat is this going to be merged soon? Can i test it already?
Thanks

**Comment by mhegazy** [comment]
@farfromrefug you can find these changes in the VSCode extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

**Comment by farfromrefug** [comment]
Thanks @mhegazy will test it right away!

**Pull request merged**
