### PR TITLE
Treat ( followed by new line as parameter context for arrow, falling back to expression

### PR DESCRIPTION
**Pull request by sheetalkamat**
Given that there are so many Issues that are getting duped to #481 and alike, i have created a branch that handles \( followed by line end as possibly arrow , this i am sure would lead to color few non arrow things as arrow (https://github.com/Microsoft/TypeScript-TmLanguage/pull/552/files#diff-a18148e1c0a6687d3019f4b439355bfbL290 will me marked as function instead of variable) but i am wondering if current behavior is better or the change here. 
Handles #481, #498, #507, #524, #539, #550, #558, #564, #574

### CODE REVIEW

**Comment by arznaar** [comment]
Hm... It's better than before. Thank you!

But there are some cases, where it's still fails to highlight properly:
tshighlighterror

**Comment by sheetalkamat** [comment]
Fixed and release [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.34 that contains the fix. Please give it a try.

**Comment by arznaar** [comment]
Awesome! Thank you!

I have looked through my repo and found another place where highlighting can be improved:
tshighlighterror2

**Comment by sheetalkamat** [comment]
Thank you for trying it out. I have fixed the reported issues and released [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version 0.0.35 that contains the fix. Please give it a try.

**Comment by jamesjryan** [comment]
@sheetalkamat works great via the limited use I gave it, what will it take to get this into VS Code upstream?

**Comment by sheetalkamat** [comment]
@jamesjryan we need more feedback and need to watch out for the bugs to see if this is really viable fix. Even though I t fixes these scenarios, it would break multiple other scenarios and bugs reported, tweaks possible and cases breaking would be factor in merging this PR. Eg. today #579  was reported and I looked through our code and there are multiple instances where this just fails..

**Comment by jamesjryan** [comment]
@sheetalkamat reporting a possible regression here - commenting a line using `cmd+/` within JSX now uses `// <SomeComponent />` as a comment, rather than `{/* <SomeComponent /> */}`.

**Comment by sheetalkamat** [comment]
@jamesjryan can you please create a issue with sample code where this is failing. Thanks.

**Comment by sheetalkamat** [comment]
FYI @mhegazy this is the PR that handles arrow function parameters that span on multiple lines

**Pull request merged**
