### PR TITLE
Add support for async / await syntax highlighting

### PR DESCRIPTION
**Pull request by ejsmith**
Not sure if this is complete, but it seems to work pretty well for us.

### CODE REVIEW

**Comment by ejsmith** [comment]
Fixes #9

**Comment by zhengbli** [comment]
Thanks for the contribution! It seems that CI test has some issues, I'll fix soon.

**Comment by DanielRosenwasser** [comment]
Since this only updates the XML files, you'll need to modify the YAML files which are the actual inputs.

**Comment by ejsmith** [comment]
Doh! I will get that updated. What tool is used to generate the xml file?

**Comment by DanielRosenwasser** [comment]
I might be wrong, but last I worked on these files, it was [AAAPackageDev](https://packagecontrol.io/packages/AAAPackageDev), a Sublime Text Plugin.

**Comment by ejsmith** [comment]
Adding a new pull request with the yaml updated.

**Pull request closed without merging**
