### PR TITLE
Fix `undefined` keyword highlighting

### PR DESCRIPTION
**Pull request by armanio123**
Removes `constant.language.undefined.ts` from the scope so that the `constant.language` scope can pick it up.

Fixes: https://developercommunity.visualstudio.com/t/JavaScript:-undefined-not-highlighted-/10358005

VS before :
image

VS After:
image

### CODE REVIEW

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
undefinded is constant so you might instead update the theme file instead. 
I am not sure if this change will break others including vscode.

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
undefinded is constant so you might instead update the theme file instead. 
I am not sure if this change will break others including vscode.

**Comment by armanio123** [comment]
By removing the scope, I'm actually making the `constant.language` scope, identify and pick up the syntax highlight for `undefined`. In Visual Studio all constants are mapped to `keyword` classification. There's no classification defined for "constants" yet.

In regard to the change, I think it will not break others. As far as I know, this file is only used by Visual Studio.

**Review by sheetalkamat — APPROVED** [review]
Sorry .. for some reason I read this as yaml for grammar instead of theme . This is correct change

**Pull request merged**
