### PR TITLE
Add support for regexp v flag

### LINKED ISSUE #1006: Support the RegExp `v` flag
The RegExp `v` flag (a.k.a. `RegExp.prototype.unicodeSets`) is now in the main ECMAScript standard and supported across all modern browsers, but TypeScript/JavaScript syntax highlighting breaks when using it. Supporting it should work similarly to https://github.com/microsoft/TypeScript-TmLanguage/pull/862.

5. If F contains any code unit other than "d", "g", "i", "m", "s", "u", "v", or "y", or if F contains any code unit more than once, throw a SyntaxError exception.
(see also https://tc39.es/ecma262/multipage/text-processing.html#sec-regexpinitialize)

### PR DESCRIPTION
**Pull request by GuestrixErik**
Fixes #1006.

### CODE REVIEW

**Comment by GuestrixErik** [comment]
@microsoft-github-policy-service agree

**Comment by nnmrts** [comment]
Any update on this?

**Comment by regseb** [comment]
:pray: Merging this pull request would fix these issues:

- https://github.com/microsoft/TypeScript-TmLanguage/issues/1006
- https://github.com/microsoft/TypeScript-TmLanguage/issues/1021
- https://github.com/microsoft/TypeScript-TmLanguage/issues/1022
- https://github.com/microsoft/vscode/issues/214090

**Comment by nnmrts** [comment]
Sorry, but: @sheetalkamat, @mjbvz

I (and probably a few others) would be more than happy if you could open up this repository for more maintainers or explain how the dependency on typescript-tmlanguage can be replaced within VSCode or the TypeScript extension with a not abandoned or at least a more maintained repository.

Thanks!

**Pull request merged**
