### PR TITLE
Fix var/let highlighting (issue 96)

### PR DESCRIPTION
**Pull request by sparecycles**
Simple problem, simple fix?

https://github.com/Microsoft/TypeScript-TmLanguage/issues/96

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Thanks for the PR! From a glance, Can you add this test?

```ts
var ^^constenum = 10;

^^constenum += 10;

^^const ^^enum { }


var ^^constable = "I am rrrrrroyal!";

^^constable += " Royal, I say!"
```

**Comment by sparecycles** [comment]
@DanielRosenwasser I added those tests and verified that the change does not affect those lines (which I believe is correct behavior).

**Comment by DanielRosenwasser** [comment]
Sorry @sparecycles, I didn't realize that the markers checked scopes to the **left**. Can you fix up the test?

```ts
var ^^constenum^^ = 10;

const^^enum^^ += 10;

const^^ enum^^ E { }


var const^^able^^ = "I am rrrrrroyal!";

const^^able^^ += " Royal, I say!"
```

**Comment by sparecycles** [comment]
@DanielRosenwasser I'm not familiar with the test framework either.  Updated to your new request.

Test still differs from prior behavior only in the 3rd and 4th line of code.

And the result looks good :wink:

screen shot 2016-02-28 at 3 15 04 am

**Comment by DanielRosenwasser** [comment]
Beautiful - @zhengbli, care to take a quick look before I pull in?

**Comment by zhengbli** [comment]
Looks good to me :+1:

**Comment by sparecycles** [comment]
@DanielRosenwasser ping.

**Comment by DanielRosenwasser** [comment]
Thanks @sparecycles!

**Comment by rob3c** [comment]
Hi, I see this was merged to master almost a month ago now, but I just updated to typescript 1.9.0-dev.20160328 (which I believe is built from master) and am still seeing the var syntax highlighting problem.

I'm using VSCode 0.10.11 with a custom settings.json file that points to my local install, and VSCode shows the local typescript version is in the status bar in the bottom right. Is there something I'm missing, or is this still not available yet? Or maybe VSCode isn't really using the local version for syntax highlighting? Thanks in advance.

**Comment by rob3c** [comment]
Ah ok - I just found the VSCode Insiders release at https://code.visualstudio.com/insiders. It handles the var/let syntax highlighting correctly for the same nightly version, so it looks like they are handling the highlighting differently beyond the installed typescript version.

**Pull request merged**
